export const navigation = [
  { slug: "consultatie-gratuita", labels: { ro: "Consultație gratuită", en: "Free consultation", ru: "Бесплатная консультация" }, mobile: true },
  { slug: "cum-functioneaza", labels: { ro: "Cum funcționează", en: "How it works", ru: "Как это работает" }, mobile: true },
  { slug: "recenzii", labels: { ro: "Recenzii", en: "Reviews", ru: "Отзывы" }, mobile: true },
  { slug: "rezultate", labels: { ro: "Rezultate", en: "Results", ru: "Результаты" }, mobile: true },
  { slug: "gabriel", labels: { ro: "Despre Gabriel", en: "About Gabriel", ru: "О Габриеле" }, mobile: true },
  { slug: "contact", labels: { ro: "Contact", en: "Contact", ru: "Контакт" }, mobile: true },
  { slug: "business", labels: { ro: "Parteneriat de afaceri", en: "Business partnership", ru: "Бизнес-партнёрство" }, mobile: true },
];

export const localeContent = {
  ro: {
    navLabel: "Meniu principal",
    mobileNavLabel: "Meniu mobil",
    menuLabel: "Deschide meniul",
    book: "Rezervă gratuit",
    skip: "Sari la conținut principal",
    location: "Strada Sevastopol 24, Sector 1, București",
    hours: "Luni–Vineri 07:00–20:00/21:00 · Sâmbătă închis · Duminică 10:00–18:00",
    navigate: "Navigare",
    legal: "Legal",
    privacy: "Confidențialitate",
    terms: "Termeni",
    cookies: "Cookies",
    disclosure: "Distribuitor Independent Herbalife. Boost Club oferă ghidare wellness și consultații educaționale. Consultația nu diagnostichează, nu tratează și nu înlocuiește îngrijirea medicală. Rezultatele variază de la persoană la persoană.",
    rights: "Toate drepturile rezervate.",
    whatsappText: "Bun%C4%83!%20Vreau%20s%C4%83%20rezerv%20o%20consulta%C8%9Bie%20gratuit%C4%83.",
    callLabel: "Sună Boost Club",
  },
  en: {
    navLabel: "Main navigation",
    mobileNavLabel: "Mobile navigation",
    menuLabel: "Open menu",
    book: "Book free",
    skip: "Skip to main content",
    location: "Strada Sevastopol 24, Sector 1, Bucharest",
    hours: "Mon–Fri 07:00–20:00/21:00 · Sat closed · Sun 10:00–18:00",
    navigate: "Navigate",
    legal: "Legal",
    privacy: "Privacy policy",
    terms: "Terms",
    cookies: "Cookies",
    disclosure: "Independent Herbalife Distributor. Boost Club provides wellness guidance and educational consultations. Consultations do not diagnose, treat or replace medical care. Results vary from person to person.",
    rights: "All rights reserved.",
    whatsappText: "Hi%21%20I%27d%20like%20to%20book%20a%20free%20consultation.",
    callLabel: "Call Boost Club",
  },
  ru: {
    navLabel: "Основная навигация",
    mobileNavLabel: "Мобильная навигация",
    menuLabel: "Открыть меню",
    book: "Записаться бесплатно",
    skip: "Перейти к основному содержанию",
    location: "Strada Sevastopol 24, Sector 1, Bucharest",
    hours: "Пн–Пт 07:00–20:00/21:00 · Сб закрыто · Вс 10:00–18:00",
    navigate: "Навигация",
    legal: "Юридическое",
    privacy: "Политика конфиденциальности",
    terms: "Условия",
    cookies: "Cookies",
    disclosure: "Независимый дистрибьютор Herbalife. Boost Club предоставляет консультации по здоровому образу жизни и образовательные консультации. Консультации не являются медицинской диагностикой, лечением или заменой медицинской помощи. Результаты варьируются от человека к человеку.",
    rights: "Все права защищены.",
    whatsappText: "%D0%97%D0%B4%D1%80%D0%B0%D0%B2%D1%81%D1%82%D0%B2%D1%83%D0%B9%D1%82%D0%B5%21%20%D0%A5%D0%BE%D1%87%D1%83%20%D0%B7%D0%B0%D0%BF%D0%B8%D1%81%D0%B0%D1%82%D1%8C%D1%81%D1%8F%20%D0%BD%D0%B0%20%D0%B1%D0%B5%D1%81%D0%BF%D0%BB%D0%B0%D1%82%D0%BD%D1%83%D1%8E%20%D0%BA%D0%BE%D0%BD%D1%81%D1%83%D0%BB%D1%8C%D1%82%D0%B0%D1%86%D0%B8%D1%8E.",
    callLabel: "Позвонить в Boost Club",
  },
};
